export const DepartmentConstant = [
  {
    Department_id: 1,
    Department_name: "Homeopathy",
    Hospital_id: 1,
    Doctor_name: "Dr. John B. Hanks",
    Is_delete: false,
    Created_at: new Date(),
  },
  {
    Department_id: 2,
    Department_name: "Dental",
    Hospital_id: 2,
    Doctor_name: "Dr. Paul A. Levine",
    Is_delete: false,
    Created_at: new Date(),
  },
  {
    Department_id: 3,
    Department_name: "Physiotherapy",
    Hospital_id: 1,
    Doctor_name: "Dr. Peyton T. Taylor",
    Is_delete: false,
    Created_at: new Date(),
  },
  {
    Department_id: 4,
    Department_name: "Dental",
    Hospital_id: 5,
    Doctor_name: "Dr. Stacey E. Mills",
    Is_delete: false,
    Created_at: new Date(),
  },
  {
    Department_id: 5,
    Department_name: "Homeopathy",
    Hospital_id: 4,
    Doctor_name: "Dr. Mark D. Okusa",
    Is_delete: false,
    Created_at: new Date(),
  },
  {
    Department_id: 6,
    Department_name: "Skin care",
    Hospital_id: 3,
    Doctor_name: "Dr. Suzanne Holroyd",
    Is_delete: false,
    Created_at: new Date(),
  },
];
